### PR TITLE
add a landpage

### PR DESCRIPTION
**Pull request by Gladear**
Add a landpage based on the work of  @georgelemon

- There is currently no logo, but it can be added easily on the top-left corner once Vinix has an official logo
- The content should be placed after, but won't be visible. I added and commented an arrow indicating that the content is after and that the user needs to scroll. It can be added back once there actually is more content
- The dark mode is only based on environment preferences (aka, using the `prefer-color-scheme` media query), there is no way to manually override it currently

Desktop (light)
desktop-light

Desktop (dark)
desktop-dark

Mobile light
mobile-light

### CODE REVIEW

**Comment by JalonSolov** [comment]
I'm not a fan of the pink.  How about a nice, plain, light gray?

**Comment by Gladear** [comment]
Here's a light grey, tell me what you think. I agree it does look a bit more like a website.

grey-bg-light
grey-bg-dark

**Comment by elimisteve** [comment]
Dark mode looks sick!

**Comment by medvednikov** [comment]
merged, the result is live:

http://vinix-os.org/

**Pull request merged**
